version: '3'
services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    ports:
      - "9042:9042" # Port for CQL clients
      - "9160:9160" # Port for Thrift clients (optional)
      - "7000:7000" # Port for inter-node communication
    command: --seeds=scylla-node1 --smp 1 # Use --smp 1 for dev/testing to limit CPU usage
    volumes:
      - scylla-data1:/var/lib/scylla # Persist data

  scylla-node2:
    image: scylladb/scylla:latest
    container_name: scylla-node2
    command: --seeds=scylla-node1 --smp 1
    volumes:
      - scylla-data2:/var/lib/scylla
    depends_on:
      - scylla-node1

  scylla-node3:
    image: scylladb/scylla:latest
    container_name: scylla-node3
    command: --seeds=scylla-node1 --smp 1
    volumes:
      - scylla-data3:/var/lib/scylla
    depends_on:
      - scylla-node1
      - scylla-node2

volumes:
  scylla-data1:
  scylla-data2:
  scylla-data3:

