version: "2"

services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  spark-master1:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master1
    depends_on:
      - zookeeper
    ports:
      - "8090:8080"
      - "7077:7077"
    environment:
      - "SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/sparkha"
      - INIT_DAEMON_STEP=setup_spark

  spark-master2:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master2
    depends_on:
      - zookeeper
    ports:
      - "8091:8080"
      - "7078:7077"
    environment:
      - "SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/sparkha"
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master1
      - spark-master2
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master1:7077,spark-master2:7077"

  spark-worker-2:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master1
      - spark-master2
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master1:7077,spark-master2:7077"

  spark-worker-3:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-3
    depends_on:
      - spark-master1
      - spark-master2
    ports:
      - "8083:8083"
    environment:
      - "SPARK_MASTER=spark://spark-master1:7077,spark-master2:7077"
